[package]
name = "owned-buf"
version = "0.2.0"
description = "An owned buffer type for reading into possibly uninitialized memory"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["nrc <nrc@ncameron.org>"]
repository = "https://github.com/nrc/owned-buf"

[dependencies]
